src/food/models.py
from datetime import datetime
from .. import db

class MenuItem(db.Model):

    item_id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(255))
    category = db.Column(db.String(255), default='')
    desc = db.Column(db.String(255))
    pic = db.Column(db.String(100))
    price = db.Column(db.String(5), default='0')

    def __str__(self):
        return self.name

class Rating(db.Model):
    r_id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(255))
    comment = db.Column(db.String(255))
    r_date = db.Column(db.DateTime(), default=datetime.now())

    def __str__(self):
        return f"{self.name}\'s review"


class Order(db.Model):
    order_id = db.Column(db.Integer(), primary_key=True)
    items_json = db.Column(db.String(5000))
    name = db.Column(db.String(255), default='')
    phone = db.Column(db.String(255), default='')
    table = db.Column(db.String(255), default='take away')
    price = db.Column(db.String(255), default='0')
    order_time = db.Column(db.DateTime(), default=datetime.now())
    bill_clear = db.Column(db.Boolean(), default=False)


class Bill(db.Model):
    bill_id = db.Column(db.Integer(), primary_key=True)
    order_items = db.Column(db.String(5000))
    name = db.Column(db.String(50), default='')
    bill_total = db.Column(db.Integer())
    phone = db.Column(db.String(25))
    bill_time = db.Column(db.DateTime(), default=datetime.now())


class BookTable(db.Model):
    book_id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), default='')
    phone = db.Column(db.String(25))
    bdate = db.Column(db.String(50))
    btime = db.Column(db.String(50))
    num_peoples = db.Column(db.Integer(), default=1)
    special = db.Column(db.String(255))

src/admin/forms.py
from wtforms import (
    widgets,
    TextAreaField
)


class CKTextAreaWidget(widgets.TextArea):
    def __call__(self, field, **kwargs):
        kwargs.setdefault('class_', 'ckeditor')
        return super(CKTextAreaWidget, self).__call__(field, **kwargs)


class CKTextAreaField(TextAreaField):
    widget = CKTextAreaWidget()

src/food/forms.py
from datetime import datetime, date
from flask_wtf import FlaskForm as Form
from wtforms import StringField, TextAreaField, IntegerField, EmailField, SelectField, BooleanField, SubmitField, DateTimeField, DateField, TimeField
from wtforms.validators import DataRequired, Length, EqualTo, URL, Email
from flask_wtf.file import FileField

NUM_PEOPLES = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')]
categories = ['Pratos', 'Sucos', 'Bebidas', 'Café']

class BookForm(Form):
    name = StringField('Nome e Sobrenome', validators=[DataRequired()])
    phone = StringField('Telefone', validators=[DataRequired()])
    bdate  = DateField('Data', default=datetime.now())
    btime  = TimeField('Horário', default=datetime.now())
    num_peoples = SelectField('Nº de Pessoas', choices=NUM_PEOPLES)
    special = TextAreaField('Pedido Especial')
    submit = SubmitField('Enviar')

class MenuForm(Form):
    name = StringField('Nome', validators=[DataRequired()])
    category = SelectField('Categoria', choices=categories)
    desc = TextAreaField('Descrição', validators=[DataRequired()])
    pic = FileField('Imagem')
    price = StringField('Valor', validators=[DataRequired()])
    submit = SubmitField(u'Upload')

src/__init__.py
from decouple import config
from flask import Flask, render_template
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet, configure_uploads, IMAGES

app = Flask(__name__)
photos = UploadSet('photos', IMAGES)
app.config.from_object(config("APP_SETTINGS"))

configure_uploads = configure_uploads(app, photos)
#app.app_context()

db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)
migrate = Migrate(app, db)


from .auth.models import User

@login_manager.user_loader
def load_user(user_id):
    # since the user_id is just the primary key of our user table, use it in the query for the user
    return User.query.get(user_id)


# Registering modules
from .auth import create_module as auth_create_module
auth_create_module(app)

from .admin import create_module as admin_create_module
admin_create_module(app)

from .food import create_module as food_create_module
food_create_module(app)

src/admin/__init__.py
from flask_admin import Admin
from .. import db
from .views import CustomModelView, CustomFileAdmin  #, PostView, CustomView
from src.auth.models import User, Role
from src.food.models import BookTable, Rating, MenuItem, Order, Bill
#from src.portfolio.models import Product
#from src.blog.models import Post, Comment, Tag

admin = Admin()


def create_module(app, **kwargs):
    admin.init_app(app)
#    admin.add_view(CustomView(name='AENTECH'))

    models = [User, Role, BookTable, Rating, MenuItem, Order, Bill]

    for model in models:
        admin.add_view(CustomModelView(model, db.session, category='Models'))

#    admin.add_view(PostView(Post, db.session, category='Models'))
    admin.add_view(CustomFileAdmin(app.static_folder, '/static/', name='Static Files'))

src/admin/views.py
from flask_admin import BaseView, expose
from flask_admin.contrib.sqla import ModelView
from flask_admin.contrib.fileadmin import FileAdmin
from flask_login import login_required, current_user

from src.auth import has_role
from .forms import CKTextAreaField


#class CustomView(BaseView):
#    @expose('/')
#    @login_required
#    @has_role('admin')
#    def index(self):
#        return self.render('index.html')


class CustomModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.is_admin   #.has_role('admin')


class CustomFileAdmin(FileAdmin):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.is_admin   #.has_role('admin')

src/food/__init__.py
def create_module(app, **kwargs):
    from .views import food_bp
    app.register_blueprint(food_bp)

src/food/views.py
from sqlalchemy import desc, func
from flask import render_template, Blueprint, request, flash, redirect, url_for, current_app
from flask_login import login_required, current_user
from datetime import date, datetime, timedelta
from itertools import groupby
from .. import db
from ..auth.models import User
from .models import MenuItem, Order, Rating, Bill, BookTable
import requests, json, ast
from .forms import MenuForm, BookForm
from .. import photos


food_bp = Blueprint(
    'food',
    __name__,
    url_prefix="/"
)

def menu():
    menu_items = MenuItem.query.all()
    items_by_category = {}

    for key, group in groupby(menu_items, key=lambda x: x.category):
        items_by_category[key] = list(group)

    return items_by_category


@food_bp.route('/', methods=['GET', 'POST'])
def home():
    all_reviews = Rating.query.order_by(Rating.r_date.desc()).all()
    items_by_category = menu()
    form = BookForm()
    if form.validate_on_submit():
    # code to validate and add book to database goes here
        name = form.name.data
        phone = form.phone.data
        bdate = form.bdate.data
        btime = form.btime.data
        num_peoples = form.num_peoples.data
        special = form.special.data

    # create a new book with the form data..
        new_book = BookTable(name=name,
                             phone=phone,
                             bdate=bdate,
                             btime=btime,
                             num_peoples=num_peoples,
                             special=special)

    # add the new book to the database
        db.session.add(new_book)
        db.session.commit()

        flash("Recebemos a sua reserva, obrigado!.", category="success")
        return redirect(url_for('.home'))
    return render_template('index.html', items_by_category=items_by_category, all_reviews=all_reviews, form=form)


@food_bp.route('/offers')
def offers(request):
    return render_template('offers.html')


@food_bp.route('/reviews', methods=['GET','POST'])
def reviews():
    if request.method == 'POST':
        if current_user.is_authenticated:
            name = current_user.name
            phone = current_user.phone
        else:
            name = 'Unknow'
            phone = 'Unknow'
        cmt = request.form.get('comment')
        date_now = datetime.now()

        review = Rating(name=name,
                        comment=cmt,
                        r_date=date_now)
        db.session.add(review)
        db.session.commit()

    all_reviews = Rating.query.order_by(Rating.r_date.desc()).all()

    return render_template('reviews.html', all_reviews=all_reviews)


@food_bp.route('/profile')
@login_required
def profile():
    if not current_user.is_authenticated:
        flash('Por favor, faça login.', category='warning')
        return redirect(url_for('auth.login'))
    return render_template('profile.html')


@food_bp.route('/manage_menu', methods=['GET', 'POST'])
@login_required
def manage_menu():
    form = MenuForm()
    if form.validate_on_submit():
        image_url = photos.save(form.pic.data)

        new_dish = MenuItem(name=form.name.data, category=form.category.data, price=form.price.data,
                              desc=form.desc.data, pic="/static/uploads/" + image_url)

        db.session.add(new_dish)
        db.session.commit()

        flash('Novo prato adicionado!', category='success')
        return redirect(url_for('.home'))

    return render_template('manage_menu.html', admin=True, form=form)



@food_bp.route('/delete_dish/<int:item_id>',  methods=['GET', 'POST'])
def delete_dish(item_id):
    product = MenuItem.query.get_or_404(item_id)
    db.session.delete(product)
    db.session.commit()
    flash('O produto foi removido com sucesso', category="info")
    return redirect(url_for('.home'))



@food_bp.route('/cart', methods=['GET','POST'])
def cart():

    if request.method == 'POST':
        if current_user.is_authenticated:
            name = current_user.name
            phone = current_user.phone
        else:
            name = 'Unknow'
            phone = 'Unknow'
        items_json = request.form.get('items_json')
        table_number = request.form.get('table_value')
        total = request.form.get('price')
        print(total)

        now = datetime.now()
#        now_ist = now + timedelta(hours=5, minutes=30)

        if table_number == 'null':
            table_number = 'Take Away'

        new_order = Order(name=name,
                          phone=phone,
                          items_json=items_json,
                          table=table_number,
                          order_time=now,
                          price=total)
        db.session.add(new_order)
        db.session.commit()

    return render_template('cart.html')


@food_bp.route('/my_orders')
@login_required
def my_orders():

    phone = current_user.phone

    orders = Order.query.filter_by(phone=phone)
    order_by_table = {}

    for key, group in groupby(orders, key=lambda x: x.table):
        order_by_table[key] = list(group)
    for table, orders in order_by_table.items():
        for ord in orders:
            items_json_str = ord.items_json
            ord.items_json = json.loads(items_json_str)


    return render_template('my_orders.html', order_by_table=order_by_table)


@food_bp.route('/all_orders')
def all_orders():

    orders = Order.query.order_by(Order.order_time.desc()).all()
    order_by_table = {}

    for key, group in groupby(orders, key=lambda x: x.table):
        order_by_table[key] = list(group)

    for table, orders in order_by_table.items():
        for ord in orders:
            items_json_str = ord.items_json
            ord.items_json = json.loads(items_json_str)


    return render_template('all_orders.html', order_by_table=order_by_table)


@food_bp.route('/generate_bill')
def generate_bill():
    t_number = request.args.get('table')

    order_for_table = Order.query.filter_by(table=t_number, bill_clear=False)
    bill_total = 0
    now = datetime.now()
#    now_ist = now + timedelta(hours=5, minutes=30)

    bill_items = []
    c_name = ''
    c_phone = ''
    for o in order_for_table:
        bill_total += int(o.price)
        o.bill_clear = True
        db.session.add(o)
        db.session.commit()

        bill_items.append({
            'order_items': o.items_json,
        })
        c_name = o.name
        c_phone = o.phone

    order_dict = {}
    for item in bill_items:
        for key, value in item.items():
            order_items = json.loads(value)
            for pr_key, pr_value in order_items.items():
                order_dict[pr_value[1].lower()] = [
                    pr_value[0], (int(pr_value[2]) * int(pr_value[0]))
                ]
    new_bill = Bill(order_items=str(order_dict),
                    name=c_name,
                    bill_total=bill_total,
                    phone=c_phone,
                    bill_time=now)
    db.session.add(new_bill)
    db.session.commit()


    return render_template('generate_bill.html', order_dict=order_dict,
        bill_total=bill_total,
        c_name=c_name,
        c_phone=c_phone,
        bill_id=new_bill.bill_id
)


@food_bp.route('/view_bills')
def view_bills():

    if not current_user.is_authenticated:
        flash('You Must be an admin user to view this!', category='warning')
        return redirect(url_for('.home'))

    all_bills = Bill.query.order_by(Bill.bill_time.desc()).all()

    for b in all_bills:
        b.order_items = ast.literal_eval(b.order_items)


    return render_template('bills.html', all_bills=all_bills)

src/templates/all_orders.html
{% extends 'base.html' %}

{% block title %}All Orders
{% endblock title %}

{% block body %}

<div style="padding: 15px 50px 15px">

  {% for table, orders in order_by_table.items() %}

  <div style="padding: 15px 5px 15px">
    
    {% if table == 'Take Away' %}
    <h3>{{ table }}</h3>
    {% else %}
    <h3>Table No : {{table}}</h3>
    {% endif %}
    <hr>
    <hr>

    {% for o in orders %}

    <h5><p>Order Time: {{ o.order_time }}</p></h5>

     {% for item_key, item_values in o.items_json.items() %}
    <b><p>{{ item_values.1 }} : {{ item_values.0 }}</p></b>
    {% endfor %}
    <b><p>Total : {{o.price}}</p></b>

    <p>Name: {{ o.name }}</p>
      {% if not o.bill_clear %}
      <button onclick="generateBill('{{table}}')">Generate Bill</button>
      {%else%}
      <b><h5>Bill Cleared</h5></b>
      {% endif %}
    <hr>
    {% endfor %}

    <hr>

  {% endfor %}

  </div>

</div>
{% endblock body %}


{%block js%}

<script src="{{ url_for('static', filename='js/all_orders.js') }}"></script>

{%endblock js%}

src/templates/bills.html
{% extends 'base.html' %}


{% block title %}Bill{% endblock title %}

{%block body%}


<div class="container col-md-6">
    <div style="display:grid;place-content:center; padding-top:25px">
        <h3>All Bills : </h3>
      </div>
    {% for b in all_bills %}
  
  <table class="table table-bordered border-dark">
  <thead>
    <tr>
      <th>Item name</th>
      <th>Qty</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    {% for item, values in b.order_items.items() %}
    <tr>
      <td>{{ item }}</td>
      <td>{{ values.0 }}</td>
      <td>{{ values.1 }}</td>
    </tr>
    {% endfor %}
    <div style='padding:50px 0px 10px'>
    <hr>
  <h5> Invoice number : {{b.bill_id}}</h5>
  <h5> Invoice time : {{b.bill_time}}</h5>
    {% if b.name != "Unknown" %}
    <h5>Name: {{ b.name }}</h5>
    <h5>Phone: {{ b.phone }}</h5>
{% endif %}
    <h5>Bill Total : {{ b.bill_total }}</h5>
    </div>
    {% endfor %}
  </tbody>
</table>

  </div>
</div>


{%endblock body%}

{% block js %}
<script>

</script>


{%endblock js%}

src/templates/cart.html
{% extends 'base.html' %}

{% block title %}Cart
{% endblock title %}

{% block body %}

<!-- <h1>Cart Page</h1> -->

<div class="container py-2">
  <h2>Review your order</h2>
  <div class="col c_cart">
  <form method="post" action="/cart">
    <input type="hidden" name="items_json" id="itemsjson">
    <input type="hidden" name="table_value" id="tableValueInput">
  <div class="my-4">

    <ul class="list-group" id="items"></ul>
    
    <ul class="list-group" style="padding:10px 15px 10px" >
      <input type="hidden" name="price" id="price_input" >
      <strong><span id="total">Total =  0</span></strong>
    </ul>


  </div>

    <button type="submit"  class="btn btn-info" style="margin:5px;" >Place Order</button>
    <button class="btn btn-warning clear_cart" style="margin:5px;" >Clear cart</button>
    <a href="{{ url_for('.home') }}"  class="btn btn-danger" style="margin:5px;" >Add More items</a>
    </form>
  </div>
</div>



{% endblock body %}

{%block js%}

<script src="{{ url_for('static', filename='js/cart.js') }}"></script>

{%endblock js%}

src/templates/generate_bill.html
{% extends 'base.html' %}


{% block title %}Bill{% endblock title %}

{%block body%}


<div class="container col-md-6">
    <div style="display:grid;place-content:center; padding-top:50px">
        <h3>Bill No : {{bill_id}} </h3>
{% if name != "Unknown" %}
    <h5>Name: {{ name }}</h5>
    <h5>Phone: {{ phone }}</h5>
{% endif %}
      </div>
        <table class="table table-bordered border-dark">
            <thead>
              <tr>
                <th>Item name</th>
                <th>Qty</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
                {% for key, value in order_dict.items() %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ value.0 }}</td>
                    <td>{{ value.1 }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    <h3 style="display:grid ;place-items:end" >Bill Total: {{ bill_total }}</h3>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button onclick="printBill()" class="btn btn-primary">Print Bill</button>
  </div>
</div>


{%endblock body%}

{% block js %}
<script src="{{ url_for('static', filename='js/generate_bill.js') }}" ></script>


{%endblock js%}

src/templates/login.html
{% extends 'base.html' %}


{%block title%}Login{%endblock title%}

{% block body %}

<style>
    .divider:after,
.divider:before {
content: "";
flex: 1;
height: 1px;
background: #eee;
}
.h-custom {
height: calc(100% - 73px);
}
@media (max-width: 450px) {
.h-custom {
height: 100%;
}
}
  </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <section class="vh-100 bg-secondary">
      <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-md-9 col-lg-6 col-xl-5">
            <img src="static/logo.png"
              class="img-fluid" alt="Sample image">
          </div>
          <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
            


            <form method="post" action="/login">
    
              <!-- Username input -->
              <div class="form-outline mb-4">
                <input type="username" id="form3Example3" name='phone' class="form-control form-control-lg"
                  placeholder="Enter Mobile Number" maxlength='10'/>
                <label class="form-label" for="form3Example3">Mobile Number</label>
              </div>
    
              <!-- Password input -->
              <div class="form-outline mb-3">
                <input type="password" id="form3Example4" name='password' class="form-control form-control-lg"
                  placeholder="Enter password" />
                <label class="form-label" for="form3Example4">Password</label>
              </div>
    
              <div class="d-flex justify-content-between align-items-center">
                <a href="#!" class="text-body">Forgot password?</a>
              </div>
    
              <div class="text-center text-lg-start mt-4 pt-2">
                <button type="submit" class="btn btn-primary btn-lg"
                  style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
                <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="/signup"
                    class="link-danger">Register</a></p>
              </div>
    
            </form>
          </div>
        </div>
      </div>
      
    </section>

{% endblock body %}

src/templates/manage_menu.html
{% extends 'base.html' %}

{%block title%} Menu {%endblock title%}

{% block body %}

{% for message in messages %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

<div class="row">
        <div class="col-lg-10 col-lg-offset-1">
                <div class="panel panel-default">
                        <form method="POST" action="{{ url_for('.manage_menu') }}" enctype="multipart/form-data">
                                <div class="panel-body">
                                        <div class="row">
                                                {{ form.csrf_token }}
                                                <div class="col-lg-6">
                                                        <div class="form-group">
                                                                <label>Nome</label>
                                                                {{ form.name(class='form-control') }}
                                                        </div>
                                                        <div class="form-group">
                                                                {{ form.category.label }}
                                                                {% if form.category.errors %}
                                                                {% for e in form.category.errors %}
                                                                <p class="help-block">{{ e }}</p>
                                                                {% endfor %}
                                                                {% endif %}
                                                                {{ form.category(class_="form-select") }}
                                                        </div>

                                                        <div class="form-group">
                                                                <label>Valor</label>
                                                                {{ form.price(class='form-control') }}
                                                        </div>

                                                </div>
                                                <div class="col-lg-6">
                                                        <div class="form-group">
                                                                <div class="form-group">
                                                                        <label>Descrição</label>
                                                                        {{ form.desc(class='form-control') }}
                                                                </div>

                                                                <label>Imagem do Produto</label>
                                                                {{ form.pic(class='form-control') }}
                                                        </div>
                                                </div>
                                        </div>
                                </div><br>

                                <div class="panel-footer">
                                        {{ form.submit }}
                                </div>
                        </form>
                </div>
        </div>
</div>

{% endblock body %}

src/templates/menu.html
{% extends 'base.html' %}

{% block title %}Menu
{% endblock title %}


{% block body %}

<div class="container col-md-12">
<center>
<h2 class="fw-bolder">
    Gestão de Cardápio, Reservas e muito mais!
</h1>
<h4 class="mb-3 mt-3">
    Cardápio sempre atualizado com edições em tempo real.
</h4></center><br>
</div><hr>

        <!-- Menu Start -->
    <div class="container-fluid py-5 text-center wow fadeIn">
<!--        <h2 class="section-title py-5">Sugestão do Chef</h2>-->
        <div class="row justify-content-center">
            <div class="col-sm-7 col-md-4 mb-5">
                <ul class="nav nav-pills nav-justified mb-3" id="pills-tab" role="tablist">
<!--                    <li class="nav-item">
                        <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#foods" role="tab" aria-controls="pills-home" aria-selected="true">Foods</a>
                    </li>-->
                        <li class="nav-item">
                            <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3 active" data-toggle="pill" href="#foods" role="tab" aria-controls="pills-home" aria-selected="true">
                                <i class="fa fa-door-open fa-2x text-secondary"></i>
                                <div class="ps-3">
                                    <small class="text-body">Terça à Domingo</small>
                                </div>
                            </a>
                        </li>
{% for category in items_by_category:  %}
                        <li class="nav-item">
                            <a class="d-flex align-items-center text-start mx-3 ms-0 pb-3" data-toggle="pill" href="#{{category}}" role="tab" aria-controls="pills-home" aria-selected="true">
                                <i class="fa fa-{{category}} fa-2x text-primary"></i>
                                <div class="ps-3">
                                    <small class="text-body">{{category}}</small>
                                </div>
                            </a>
                        </li>
{% endfor %}
                </ul>
            </div>
        </div>
        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="foods" role="tabpanel" aria-labelledby="pills-home-tab">
                <div class="row">
                    <div class="col-md-4">
                        <div class="card border my-3 my-md-0">
                            <img src="{{ url_for ('static', filename='uploads/tandoor_roti.png') }}" alt="" class="rounded-0 card-img-top mg-responsive">
                            <div class="card-body">
                                <h1 class="text-center">R$25,00</h1>
                                <h4>Reiciendis Laborum </h4>
                                <p class="text-dark">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa provident illum officiis fugit laudantium voluptatem sit iste delectus qui ex. </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card border my-3 my-md-0">
                            <img src="{{ url_for ('static', filename='uploads/roasted_papad.png') }}" alt="" class="rounded-0 card-img-top mg-responsive">
                            <div class="card-body">
                                <h1 class="text-center">R$12,00</h1>
                                <h4>Adipisci Totam</h4>
                                <p class="text-dark">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa provident illum officiis fugit laudantium voluptatem sit iste delectus qui ex. </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card border my-3 my-md-0">
                            <img src="{{ url_for ('static', filename='uploads/masala_papad_uLBfzPx.png') }}" alt="" class="rounded-0 card-img-top mg-responsive">
                            <div class="card-body">
                                <h1 class="text-center">R$8,00</h1>
                                <h4>Dicta Deserunt</h4>
                                <p class="text-dark">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa provident illum officiis fugit laudantium voluptatem sit iste delectus qui ex. </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% for category, products in items_by_category.items():  %}
            <div class="tab-pane fade" id="{{category}}" role="tabpanel" aria-labelledby="pills-profile-tab">
                <div class="row">
{% for i in products: %}
                    <div class="col-md-3 my-3 my-md-0">
                        <div class="card border">
                            <img src="{{i.pic}}" alt="" class="rounded-0 card-img-top mg-responsive">
                            <div class="card-body">
                                <h1 class="text-center">R${{i.price}}</h1>
                                <h4>{{i.name}}</h4>
                                <p class="dark">{{i.desc}}</p>
                            </div>
                        </div>
                    </div>
{% endfor %}
                </div>
            </div>
{% endfor %}
        </div>
    </div>
        <!-- Menu End -->


{% for category, menu_items in items_by_category.items() %}
  <h3 style="margin:40px 25px 5px">{{category}}:</h3>
<div class="row justify-content-center">
{% for i in menu_items %}
<div class="card" style="width: 18rem; margin:20px 20px 10px; ">
  <img src="{{i.pic}}" class="card-img-top"  style='padding:10px 0px 0px; max-height:250px;'>
  <div class="card-body">
    <h4 class="card-title" id="namepr{{i.item_id}}" >{{i.name}}</h4>
    <h5 class="card-title">R$ <span id="pricepr{{i.item_id}}" >{{i.price}}</span></h5>
    <p class="card-text">{{i.desc}}</p>
    {% if current_user.is_admin %}
    <form action="{{ url_for('food.delete_dish', item_id=i.item_id) }}" method="post">
    <button class="btn btn-danger" type="submit">Delete</button>
    </form>

    {% else %}
    <span id="divpr{{i.item_id}}" class="divpr" >
    <button  id="pr{{i.item_id}}" class="btn btn-danger cart">Add to cart</button>
    </span>
    {% endif %}
  </div>
</div>
{% endfor %}
</div>
{% endfor %}


<div class="d-flex justify-content-center" style="padding:25px 0px 50px;">
  <a href='/cart' ><button type="submit" class="btn btn-outline-warning">Go To Cart</button> </a>
</div>


{% endblock body %}


{%block js%}

<script src="{{ url_for('static', filename='js/menu.js') }}"></script>

{%endblock js%}

src/templates/offers.html
{% extends 'base.html' %}

{% block title %}Offers
{% endblock title %}

{% block body %}

<h1>Offers Page</h1>

{% endblock body %}